microsoft/vscode-apimanagement

src/explorer/editors/Editor.ts, src/explorer/editors/policy/BasePolicyEditor.ts
skip policy save when user closes the dialog
#19
=> skip policy save when user closes the dialog

resources/dark/namedvalue.svg, resources/light/namedvalue.svg, src/explorer/NamedValueTreeItem.ts
=> add namedvalue icon

src/openApi/OpenApiParser.ts
Avoid repeating https://https://hostname/basepath in server uri
=> Remove repeating protocol segments

package.json, package.nls.json, resources/projectFiles/Context.cs, resources/projectFiles/_ViewImports.cshtml, src/commands/openWorkingFolder.ts, src/commands/setupWorkingFolder.ts, src/constants.ts, src/explorer/editors/policy/BasePolicyEditor.ts, src/extension.ts, src/utils/cpUtils.ts, src/utils/dotnetUtils.ts, src/utils/extensionUtil.ts, src/utils/fsUtil.ts, src/utils/openUrl.ts, src/utils/vscodeUtils.ts
=> Experimental: Support Intellisense for policy expressions by leveraging razor vscode tooling

resources/projectFiles/_ViewImports.cshtml, src/commands/setupWorkingFolder.ts
#45 
Add NewtonSoft.Json support OOB during Initialize of the extension workspace folder
=> add newtonsoft package during initialize

.azure-pipelines/common/build.yml, .azure-pipelines/linux/xvfb.init, .azure-pipelines/main.yml, .azure-pipelines/windows/intellinav.yml, package-lock.json, package.json
I noticed builds were failing and this should port over a few fixes that were already in our other repos.
1. Update VM images: https://github.com/microsoft/vscode-azurefunctions/pull/1840
1. Fix tests on linux build machine: https://github.com/microsoft/vscode-azureappservice/pull/1391
1. Explicitly specify triggers: https://github.com/microsoft/vscode-azurefunctions/pull/1975
=> Update Azure Pipelines config

package.json
=> Reorder select menu

src/commands/extract.ts, src/utils/dotnetUtils.ts
=> Add checking for dotnet version

src/commands/generateNewGatewayToken.ts, src/constants.ts
=> Change the token expire limit and add more error details

CHANGELOG.md, package-lock.json, package.json, src/commands/createService/ServiceCreateStep.ts, src/openApi/OpenApiParser.ts
=> Fix OpenAPI host url and provisioning

package.json, resources/diff.svg, src/commands/openDiffEditor.ts, src/explorer/editors/Editor.ts, src/explorer/editors/arm/BaseArmResourceEditor.ts, src/explorer/editors/openApi/OpenApiEditor.ts, src/explorer/editors/policy/BasePolicyEditor.ts, src/extension.ts, src/operationConsole/OperationConsole.ts
Enable policy/OAS diffing;
fix debugging header issue
close #130 
close #50
=> Add policy/OAS diff and fix debugging header

package.json, package.nls.json, src/commands/addApiFilter.ts, src/commands/removeApiFilter.ts, src/explorer/ApisTreeItem.ts, src/extension.ts
This PR adds a simple filter on `displayName` as suggested with #132
=> implement API filter on displayName

package.json, src/commands/debugPolicies/debugPolicy.ts, src/commands/generateFunctions.ts
=> Fix stencil and debugging

src/explorer/ApiTreeItem.ts
=> Fix switch revision

README.md
failed to upload the new version with error
Extension validation error
Error processing 'ms-azuretools.vscode-apimanagement' SVG reference in file '/extension/README.md'. Your reference to the SVG image ‘https://vsmarketplacebadge.apphb.com/version/ms-azuretools.vscode-apimanagement.svg’ is not supported. Please see https://aka.ms/vsmarketplace_badge for more details.
update vs market place batches 
https://vsmarketplacebadges.dev/
=> Update README.md marketplace badges

CHANGELOG.md, package-lock.json, package.json
=> Fixed: load apim instances when expanding an Azure subscription

src/constants.ts, src/explorer/AzureAccountTreeItem.ts, src/uiStrings.ts
show select subscriptions when no subscription selected
=> perf: select sub when no subs show

package.json, package.nls.json, resources/prompts/explainPolicy.md, src/commands/explainPolicy.ts, src/extension.ts, src/utils/promptUtils.ts, test/promptUtils.test.ts
Add entry to Copilot menu to explain APIM policy
1. If user selects any content, only explain the selected content
2. If user doesn't select any content, explain the whole file
=> feat: Add copilot entry to explain APIM policy

resources/prompts/explainPolicy.md
Improve the explain policy prompt based on evaluation result
=> feat: improve explain policy prompt

package.json
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2420703/?view=edit
=> fix: activate extension when open xml files to enable IntelliSense

src/explorer/AuthorizationProvidersTreeItem.ts
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2422450/?view=edit
=> fix: remove preview suffix in credential manager

src/commands/importFunctionApp/importFunctionApp.ts, src/commands/importOpenApi.ts, src/commands/importWebApp/importWebApp.ts, src/commands/manageNamedValue.ts, src/commands/manageSubscriptions.ts
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2426558/?view=edit
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2426139/?view=edit
=> fix: typo in extension

src/constants.ts, src/explorer/McpServersTreeItem.ts, src/extension.ts
Show learn more information when no MCP listed
=> feat: show learn more information when no MCP listed

CHANGELOG.md, package.json
1. Bump extension version to 1.2.0
2. Add changelog
=> build: bump version to 1.2.0 and add changelog

CHANGELOG.md
Update readme based on feedback from https://github.com/microsoft/vscode-apimanagement/pull/424
=> build: update readme

src/azure/apim/ApimService.ts
Use lower api version based on discussion with service team
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2471131/?view=edit
=> fix: use lower api version for MCP related requests

src/tools/availablePoliciesTool.ts
Add telemetry for language model tool
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2477066
=> fix: no telemetry for language model tool

package-lock.json, package.json, src/tools/availablePoliciesTool.ts, src/utils/fileUtils.ts, test/availablePoliciesTool.test.ts
1. Add ut for language model tool
2. Throw exception in language model tool instead of return an error message
3. Do not use `fs-extra` package to read file to make the code easy to mock
=> test: add ut for lm tool and throw exception when fail
